" My choice of font changes depending on which operating system I'm using;
" these are both workable monospace fonts, but Ubuntu Mono doesn't render very
" nicely on Windows a lot of the time
if has("unix")
    silent! set guifont=Ubuntu\ Mono\ 12
else
    silent! set guifont=Consolas:h11
endif

" Use the system GUI clipboard; use console dialogs instead of popup windows;
" use the gVim icon
set guioptions=aci

" When the GUI starts, t_vb is reset to its default value, so it's necessary
" to repeat this line from my .vimrc file that turns off visual bells
set visualbell t_vb=

