# If running Bash, source .bashrc.
if [ -n "$BASH_VERSION" ]; then
    if [ -e "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# Add ~/bin to the path if it exists.
if [ -d "$HOME/bin" ]; then
    PATH="$HOME/bin:$PATH"
fi

# Environment variables.
export LANG=en_NZ.UTF-8
export NCURSES_NO_UTF8_ACS=1

