# If running Bash, source .bashrc.
if [ -n "$BASH_VERSION" ]; then
    if [ -e "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# Add ~/bin to the path if it exists.
if [ -d "$HOME/bin" ]; then
    PATH="$HOME/bin:$PATH"
fi

# Add machine-specific locale file if it exists.
if [ -e "$HOME/.bash_locale" ]; then
    . "$HOME/.bash_locale"
fi

# None of this UTF8 drawing characters nonsense.
export NCURSES_NO_UTF8_ACS=1

