# Only if interactive
[ -z "$PS1" ] && return

# Append to history, no duplicate lines
shopt -s histappend
HISTCONTROL=ignoreboth

# Recheck window size after each command
shopt -s checkwinsize

# Current root/chroot
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# Set xterm title
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# Set xterm colors
case "$TERM" in
xterm*)
    TERM=xterm-256color
    export TERM
    ;;
*)
    ;;
esac

# Aliases
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# Auto completion
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

