# Don't do anything if not running interactively
if [[ $- != *i* ]]; then
    return
fi

# Keep plenty of history
HISTFILESIZE=1000000
HISTSIZE=1000000

# Ignore duplicate commands and whitespace in history
HISTCONTROL=ignoreboth

# Keep the times of the commands in history
HISTTIMEFORMAT='%F %T  '

# Don't tell me about mail
unset MAILCHECK

# Never beep at me
if command -v setterm &>/dev/null; then
    setterm -bfreq 0
fi

# Turn off flow control and control character echo
if command -v stty &>/dev/null; then
    stty -ixon -ctlecho
fi

# Use completion, if available
if [[ -r /etc/bash_completion ]]; then
    source /etc/bash_completion
fi

# Load any supplementary scripts
if [[ -d $HOME/.bashrc.d ]]; then
    for file in "$HOME"/.bashrc.d/*; do
        source "$file"
    done
fi
unset file

