# Source .bashrc if it exists.
[[ -e "$HOME/.bashrc" ]] && source "$HOME/.bashrc"

# Add various paths if they exit.
[[ -d "${HOME}/bin" ]] && PATH="${HOME}/bin:${PATH}"
[[ -d "/usr/local/mysql/bin" ]] && PATH="/usr/local/mysql/bin:${PATH}"
[[ -d "/usr/local/pgsql/bin" ]] && PATH="/usr/local/pgsql/bin:${PATH}"

# None of this UTF8 drawing characters nonsense.
export NCURSES_NO_UTF8_ACS=1

